jsonapi/config/routes.rb
Rails.application.routes.draw do

  resources :home

  root to: 'home#index'

end

jsonapi/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

jsonapi/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

jsonapi/app/controllers/home_controller.rb
class HomeController < ApplicationController
  require 'rest-client'
  require 'json'

  BASE_URL = "http://localhost:3009"

  def index
    value = RestClient.get "#{BASE_URL}/users"

    @users = JSON.parse(value, :symbolize_names => true)
  end

  def new
    
  end

  def create
    url = "#{BASE_URL}/users"
    payload = params.to_json
    value = RestClient::Resource.new(url)
    begin
      value.post payload, :content_type => "application/json"
      flash[:notice] = "User saved"
      redirect_to root_url
    rescue Exception => e
      flash[:error] = "User failed to save"
      render :new
    end
  end

  def edit
    url = "#{BASE_URL}/users/#{params[:id]}"
    value = RestClient::Resource.new(url)
    
    users = value.get
    @user = JSON.parse(users, :symbolize_names => true)
  end

  def update
    url = "#{BASE_URL}/users/#{params[:id]}"
    payload = params.to_json
    value = RestClient::Resource.new(url)

    begin
      value.put payload, :content_type => "application/json"
      flash[:notice] = "User Updated"      
    rescue Exception => e
      flash[:error] = "User failed to save"
    end
      redirect_to root_url
  end
  
  def destroy
    url = "#{BASE_URL}/users/#{params[:id]}"
    value = RestClient::Resource.new(url)
    
    begin
      value.delete
      flash[:notice] = "User Deleted" 
    rescue Exception => e
      flash[:error] = "User failed to save"
    end
      redirect_to root_url        
  end
  
  
end

jsonapi/app/helpers/application_helper.rb
module ApplicationHelper
end

jsonapi/app/helpers/home_helper.rb
module HomeHelper
end

jsonapi/app/views/home/edit.html.erb
<%= form_tag home_path, method: :put do %>
  First Name: <%= text_field_tag :firstName, @user[:firstName] %> <br/>
  Last Name: <%= text_field_tag :lastName, @user[:lastName] %> <br/>
  Email: <%= text_field_tag :email, @user[:email] %> <br/>

  <%= submit_tag "update"%>
<% end %>

jsonapi/app/views/home/index.html.erb
<p id="notice"><%= notice %></p>

<%= link_to "New User", new_home_path %>

<%if @users.present? %>
  <p>List Users</p>
  <table width="100%">
    <tr>
      <td>ID</td>
      <td>first_name</td>
      <td>last_name</td>
      <td>email</td>
      <td>Action</td>
    </tr>
    
    <%@users.each do |u|%>
    <tr>
      <td><%=u[:id]%></td>
      <td><%=u[:firstName]%></td>
      <td><%=u[:lastName]%></td>
      <td><%=u[:email]%></td>      
      <td>
        <%= link_to "Edit", edit_home_path(u[:id]) %> |
        <%= link_to "Delete", home_path(u[:id]), method: :delete, data: { confirm: 'Are you sure?' } %>
      </td>
    </tr>
   <%end%>
  </table>
<%else%>
  <p>No User is Found</p>
<%end%>

jsonapi/app/views/home/new.html.erb
<%= form_tag home_index_path, method: :post do %>
  First Name: <%= text_field_tag :firstName%> <br/>
  Last Name: <%= text_field_tag :lastName%> <br/>
  Email: <%= text_field_tag :email%> <br/>

  <%= submit_tag "save"%>
<% end %>

jsonapi/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jsonapi</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>